### ISSUE TITLE
Very high memory usage of 'attribute' module

### ISSUE THREAD

**Issue by raar1** [C3S-attribution-service/climexp4c3s#4]
I was testing (interactively) with the following command:
```
./attribute /testdata/txtx260.nc none GEV assume shift mon 1 begin2 1901 end2 2000 plot test.plot
```

If docker is allocated 4G of memory we get the following error:
```
Operating system error: Cannot allocate memory
Allocation would exceed memory limit
```

Upping the memory to 15G worked, although I don't know what the actual threshold is. The stack size was 'unlimited' (according to ulimit). Over 4G of memory is excessive for such a small input file and might cause problems if the image is to be used as part of the cds toolbox.

**Comment by goord** [comment]
On my ubuntu laptop running that command takes 1% of my 16GB of memory.

This seems like a docker-on-macos bug (or feature)

**Comment by raar1** [comment]
Could well be, there have been loads of irritating things about using docker on mac. OK, hopefully that's not something to be concerned about, so I'll close this issue for now.
